[tools]
"nix:home-manager" = "2024-04-23"
"nix:neovim" = "0.11.5"
"nix:vimPlugins.nvim-treesitter" = "2025-05-24"

[env]
NVIM_TREESITTER_PATH = "{{exec(command='mise where nix:vimPlugins.nvim-treesitter')}}"

[settings]
experimental = true